import type { Copy } from '@fuda/i18n'
import type { SignInFailure } from '@fuda/libs/auth'
import type { Reason } from '@fuda/sdk'

const EN = {
  auth: {
    checking: 'Checking your session…',
    description: 'Use your passkey to create an account or sign in.',
    failed: 'Could not check your session',
    failures: {
      network: 'The sign-in service could not be reached. Try again.',
      rejected: 'The signature was not accepted. Request a fresh sign-in.',
      unavailable: 'The sign-in service could not verify this wallet. Try again later.',
      wallet: 'The wallet request was cancelled or unavailable. You can try again.',
    } satisfies Record<SignInFailure, string>,
    preserved: 'Your saved session is still on this device.',
    redirecting: 'Taking you to fuda…',
    signOutLocal: 'Sign out locally',
    title: 'Your passes, in one place',
  },
  chrome: {
    language: 'Language',
    theme: { control: 'Theme', dark: 'Dark', light: 'Light', system: 'System' },
  },
  common: { cancel: 'Cancel', member: 'Member', retry: 'Retry' },
  landing: {
    description: 'Keep your passes close. Show one when you arrive.',
    open: 'Open your passes',
    start: 'New here? Open a card link or scan its QR code to get started.',
    subtitle: 'Ready at the door.',
    title: 'Your membership.',
  },
  nav: {
    label: 'Member navigation',
    private: '+Private',
    rights: 'Your passes',
    settings: 'Settings',
    signed: 'Enter',
  },
  passes: {
    active: 'ACTIVE',
    address: 'Holder address',
    browserWallet: 'Use browser wallet',
    connectionFailed: 'Could not connect wallet.',
    idle: 'Enter a holder address to read its on-chain rights.',
    indexUnavailable: 'index unavailable; showing passes saved on this device',
    invalidAddress: 'Enter a valid holder address.',
    issuer: 'issuer',
    loading: 'Loading rights…',
    lookup: 'Look up',
    lookupAnother: 'Look up another public address',
    noMatches: 'No matching passes.',
    noPasses: 'No passes found yet.',
    noRights: 'No rights found for this holder.',
    pass: 'Pass',
    placeholder: '0x… holder address',
    privateNotice: 'This is a +Private pass. Open Private rights to recover it.',
    privateRights: 'Private rights',
    recoveryFailed: 'Could not recover this pass:',
    revoked: 'REVOKED',
    saved: 'Saved on this device',
    search: 'Search passes',
    stampCount: (total: number, goal: number): string => `${total} / ${goal} stamps`,
    stamps: 'Stamp progress',
    start: 'Open a card link or scan a card QR code to get started.',
    tier: 'tier',
    todayCount: (today: number, limit: number): string => `${today} / ${limit} today`,
    unavailable: 'Status unavailable',
    usage: 'usage model',
    view: 'View pass',
  },
  settings: {
    appearance: 'Appearance',
    changeLanguage: 'Change language',
    changeTheme: 'Change theme',
    description:
      'This removes the member session from this browser. Passes saved on this device and your passkey remain.',
    keep: 'Keep session',
    lookupDescription:
      'Check passes held by another public address. This does not change your account or save the address.',
    signOut: 'Sign out',
    title: 'Sign out of fuda?',
  },
}

export const MEMBER_COPY = {
  en: EN,
  ja: {
    auth: {
      checking: 'サインイン状態を確認中…',
      description: 'パスキーで登録・サインインできます。',
      failed: 'サインイン状態を確認できませんでした',
      failures: {
        network: '認証サービスに接続できませんでした。もう一度お試しください。',
        rejected: '署名を確認できませんでした。サインインをやり直してください。',
        unavailable: 'このウォレットを確認できませんでした。しばらくしてからお試しください。',
        wallet: 'ウォレットの操作が中断されたか、利用できませんでした。もう一度お試しください。',
      },
      preserved: 'サインイン情報はこの端末に保存されています。',
      redirecting: 'fuda に移動しています…',
      signOutLocal: 'この端末でサインアウト',
      title: 'あなたのパスを、ひとつに。',
    },
    chrome: {
      language: '言語',
      theme: { control: 'テーマ', dark: 'ダーク', light: 'ライト', system: '端末に合わせる' },
    },
    common: { cancel: 'キャンセル', member: 'メンバー', retry: '再試行' },
    landing: {
      description: 'パスを開いて、到着したら見せるだけ。',
      open: 'パスを開く',
      start: 'はじめての方は、カードのリンクかQRコードからどうぞ。',
      subtitle: 'いつも手元に。',
      title: '会員証を、',
    },
    nav: {
      label: 'メンバーメニュー',
      private: '+Private',
      rights: 'あなたのパス',
      settings: '設定',
      signed: '入場',
    },
    passes: {
      active: '有効',
      address: '保有者のアドレス',
      browserWallet: 'ブラウザのウォレットを使う',
      connectionFailed: 'ウォレットに接続できませんでした。',
      idle: '保有者のアドレスを入力すると、オンチェーンの権利を確認できます。',
      indexUnavailable: '一覧を取得できないため、この端末に保存したパスを表示しています。',
      invalidAddress: '有効な保有者のアドレスを入力してください。',
      issuer: '発行者',
      loading: 'パスを読み込み中…',
      lookup: '検索',
      lookupAnother: 'ほかの公開アドレスを検索',
      noMatches: '一致するパスはありません。',
      noPasses: 'パスはまだありません。',
      noRights: 'このアドレスの権利は見つかりませんでした。',
      pass: 'パス',
      placeholder: '0x… 保有者のアドレス',
      privateNotice: 'これは +Private のパスです。+Private を開いて復元してください。',
      privateRights: '+Private を開く',
      recoveryFailed: 'パスを復元できませんでした：',
      revoked: '失効',
      saved: 'この端末に保存済み',
      search: 'パスを検索',
      stampCount: (total: number, goal: number): string => `スタンプ ${total} / ${goal}`,
      stamps: 'スタンプの獲得状況',
      start: 'カードのリンクを開くか、QRコードを読み取ってください。',
      tier: 'ランク',
      todayCount: (today: number, limit: number): string => `今日 ${today} / ${limit}`,
      unavailable: '状態を確認できません',
      usage: '利用形式',
      view: 'パスを見る',
    },
    settings: {
      appearance: '表示',
      changeLanguage: '言語を変更',
      changeTheme: 'テーマを変更',
      description: 'このブラウザのサインイン情報を削除します。端末に保存したパスとパスキーは残ります。',
      keep: 'サインインを続ける',
      lookupDescription:
        '別の公開アドレスが持つパスを確認します。アカウントの変更やアドレスの保存は行いません。',
      signOut: 'サインアウト',
      title: 'fuda からサインアウトしますか？',
    },
  },
} satisfies Copy<typeof EN>

export type MemberCopy = typeof EN

export const PASS_REASON_JA = {
  ALREADY_USED: '使用済み',
  BAD_CHALLENGE: '確認用の情報が無効です',
  BAD_SIGNATURE: '署名を確認できません',
  DELEGATION_CONFIG_MISSING: '発行権限の設定がありません',
  DELEGATION_UNAVAILABLE: '発行権限を確認できません',
  EXPIRED: '期限切れ',
  ISSUER_NOT_DELEGATED: '発行者の権限を確認できません',
  LEVEL_REQUIRED: '署名での確認が必要です',
  NOT_FOUND: '見つかりません',
  NOT_YET_VALID: '有効期間前',
  NO_DELEGATION: '発行権限がありません',
  OK: '有効',
  REVOKED: '失効',
  UNKNOWN_USAGE_MODEL: '対応していない利用形式です',
  WRONG_SCHEMA: '対応していない形式です',
} satisfies Record<Reason, string>
